### PR TITLE
ataraxia linux has been removed dut to their service manager changes

### PR DESCRIPTION
**Pull request by Zaryob**
If you wanna be familiar with this issue. You can look at Atatraxia's last release data and their iso shared on [Github](https://github.com/ataraxialinux/ataraxia/releases/tag/200913)

ataraxia is currently excommunicated.

https://github.com/muellermartin/nosystemd.org/issues/25

### CODE REVIEW

**Comment by paledega** [comment]
image

**Comment by psposito** [comment]
Well done!

It also has to be removed from https://nosystemd.org/

Regards

**Comment by muellermartin** [comment]
Thanks for your contribution! I will also update the website.

**Comment by protonesso** [comment]
Bye lads we had a good time

**Pull request merged**
